name: Code Review using Qwen/QwQ-32B

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch full history

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install transformers sentencepiece torch huggingface_hub

      - name: Cache Hugging Face model
        uses: actions/cache@v3
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-qwen-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-qwen-

      - name: Get list of changed files
        id: files
        run: |
          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | jq -R -s -c 'split("\n")[:-1]')
          else
            files=$(git diff --name-only HEAD^ HEAD | jq -R -s -c 'split("\n")[:-1]')
          fi
          echo "changed_files=$files" >> $GITHUB_ENV

      - name: Run code review with Qwen/QwQ-32B
        run: |
          python review_code.py '${{ env.changed_files }}'
