name: Code Review using CodeBERT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install transformers torch

      - name: Get list of changed files
        id: files
        run: |
          # Get the list of files changed in the PR or push
          files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "changed_files=$files" >> $GITHUB_ENV

      - name: Run code review with CodeBERT
        run: |
          python review_code.py "${{ env.changed_files }}"
