name: Code Review

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install transformers sentencepiece torch huggingface_hub

      - name: Cache CodeLlama model
        uses: actions/cache@v2
        with:
          path: ~/.cache/huggingface
          key: ${{ runner.os }}-transformers-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-transformers-

      - name: Get list of changed files
        id: files
        run: |
          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          else
            files=$(git diff --name-only HEAD^ HEAD)
          fi
          echo "changed_files=$files" >> $GITHUB_ENV

      - name: Run code review with CodeLlama
        run: |
          python review_code.py "${{ env.changed_files }}"
