name: Code Review using CodeBERT

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  code_review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install transformers torch

      - name: Get list of changed files
        id: files
        run: |
          # Check if the event is a pull_request
          if [[ $GITHUB_EVENT_NAME == "pull_request" ]]; then
            # For PR, compare the base and head commits
            files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          else
            # For push event, compare the current commit with the last commit (use HEAD)
            files=$(git diff --name-only HEAD^ HEAD)
          fi
          echo "changed_files=$files" >> $GITHUB_ENV  

      - name: Run code review with CodeBERT
        run: |
          python review_code.py "${{ env.changed_files }}"
